name: oat
channels:
  - conda-forge

dependencies:
  - python=3.10
  - pip

  - einops
  - hydra-core
  - wandb
  - dill
  - zarr
  - numba
  - diffusers
  - accelerate
  - gsutil
  - transformers
  - av
  - gymnasium

  - pip:
      # pytorch
      - torch
      - torchvision
      - --extra-index-url https://download.pytorch.org/whl/nightly/cu129

      - vector-quantize-pytorch
      - robomimic==0.2.0
      - robosuite==1.4.0
      - easydict
      - bddl
      - cloudpickle
